import { Paella } from './paella/paella';

export const PAELLAS: Paella[] = [
  { id: 0, nombre: 'Paella de pollo y conejo', descripcion: 'Paella de pollo y conejo', cocinero: 'Jose', foto: 'drybhBDTHRRcfgfhc', ubicacion: 'quart de poblet', dias: 3, plazas: 6, plazas_libres: 4, fecha:'1990-01-24 07:59:45', precio: 4, categoria: 3, mascota: true, ver_hacer_paella: false, ninos: true, usuario_id: 2 },
  { id: 1, nombre: 'Paella de costillas y verdura', descripcion: 'Paella de costillas y verdura', cocinero: 'Jonas', foto: 'drybhBDTHRRcfgfhc', ubicacion: 'alzira', dias: 4, plazas: 6, plazas_libres: 4, fecha:'1990-01-24 07:59:45', precio: 3, categoria: 5, mascota: false, ver_hacer_paella: true, ninos: false, usuario_id: 1 },
  { id: 2, nombre: 'Paella vegana', descripcion: 'Paella vegana', cocinero: 'John', foto: 'drybhBDTHRRcfgfhc', ubicacion: 'donde tu quieras mi niño', dias: 5, plazas: 6, plazas_libres: 4, fecha:'1990-01-24 07:59:45', precio: 5, categoria: 6, mascota: true, ver_hacer_paella: false, ninos: true, usuario_id: 8 },
  { id: 3, nombre: 'Paella de marisco', descripcion: 'Paella de marisco', cocinero: 'Jorge', foto: 'drybhBDTHRRcfgfhc', ubicacion: 'almusafes', dias: 6, plazas: 6, plazas_libres: 4, fecha:'1990-01-24 07:59:45', precio: 4.5, categoria: 8, mascota: true, ver_hacer_paella: true, ninos: true, usuario_id: 5 },
  { id: 4, nombre: 'Paella con pollo sin verdura', descripcion: 'Paella con pollo sin verdura', cocinero: 'Joe', foto: 'drybhBDTHRRcfgfhc', ubicacion: 'quart de poblet', dias: 1, plazas: 6, plazas_libres: 4, fecha:'1990-01-24 07:59:45', precio: 6, categoria: 3, mascota: true, ver_hacer_paella: false, ninos: false, usuario_id: 2 },
  { id: 5, nombre: 'Paella mixta', descripcion: 'Paella mixta', cocinero: 'Joseph', foto: 'drybhBDTHRRcfgfhc', ubicacion: 'canadá', dias: 5, plazas: 6, plazas_libres: 4, fecha:'1990-01-24 07:59:45', precio: 8, categoria: 2, mascota: false, ver_hacer_paella: true, ninos: true, usuario_id: 4 },
  { id: 6, nombre: 'Arros al forn', descripcion: 'Arros al forn', cocinero: 'Jonathan', foto: 'drybhBDTHRRcfgfhc', ubicacion: 'alboraya', dias: 3, plazas: 6, plazas_libres: 4, fecha:'1990-01-24 07:59:45', precio: 7, categoria: 1, mascota: true, ver_hacer_paella: false, ninos: true, usuario_id: 7 },
  { id: 7, nombre: 'Paella con piña', descripcion: 'Paella con piña', cocinero: 'Peter', foto: 'drybhBDTHRRcfgfhc', ubicacion: 'ahi detras', dias: 1, plazas: 6, plazas_libres: 4, fecha:'1990-01-24 07:59:45', precio: 9, categoria: 3, mascota: false, ver_hacer_paella: true, ninos: false, usuario_id: 3 },
];
